name: Update Flake

on:
  schedule:
    - cron: "0 0 * * 0" # Runs at midnight (00:00) on Sundays
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  update-flake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Nix
        uses: cachix/install-nix-action@v31

      - name: Update Nix flake
        run: |
          nix flake update --commit-lock-file
        env:
          GIT_AUTHOR_NAME: "GitHub Actions"
          GIT_AUTHOR_EMAIL: "actions@github.com"
          GIT_COMMITTER_NAME: "GitHub Actions"
          GIT_COMMITTER_EMAIL: "actions@github.com"

      - name: Push changes
        run: git push origin HEAD:refs/heads/update-flake
        env:
          GIT_AUTHOR_NAME: "GitHub Actions"
          GIT_AUTHOR_EMAIL: "actions@github.com"
          GIT_COMMITTER_NAME: "GitHub Actions"
          GIT_COMMITTER_EMAIL: "actions@github.com"

      - name: Create a Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          title: "Update flake.lock"
          body: "Automated update of flake.lock file by GitHub Actions"
          base: main
          branch: update-flake
